
Thread #x was created
   at 0x........: clone (in /...libc...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (hg03_inherit.c:46)

Thread #x is the program's root thread

Possible data race during write of size 4 at 0x........ by thread #x
   at 0x........: t2 (hg03_inherit.c:28)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
 This conflicts with a previous read of size 4 by thread #x
   at 0x........: main (hg03_inherit.c:60)
 Location 0x........ is 0 bytes inside shared[1],
 declared at hg03_inherit.c:11, in frame #0 of thread x

Possible data race during write of size 4 at 0x........ by thread #x
   at 0x........: t2 (hg03_inherit.c:29)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: start_thread (in /lib/libpthread...)
   by 0x........: clone (in /...libc...)
 This conflicts with a previous read of size 4 by thread #x
   at 0x........: main (hg03_inherit.c:60)
 Location 0x........ is 0 bytes inside shared[1],
 declared at hg03_inherit.c:11, in frame #0 of thread x

ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
