
Thread #2 was created
   at 0x........: clone (in /...libc...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc21_pthonce.c:86)

Thread #3 was created
   at 0x........: clone (in /...libc...)
   by 0x........: pthread_create@GLIBC_ (in /lib/libpthread...)
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc21_pthonce.c:86)

Possible data race during write of size 4 at 0x........
   at 0x........: child (tc21_pthonce.c:74)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   by 0x........: ...
   by 0x........: ...
  Old state: shared-readonly by threads #2, #3
  New state: shared-modified by threads #2, #3
  Reason:    this thread, #3, holds no consistent locks
  Location 0x........ has never been protected by any lock
  Location 0x........ is 0 bytes inside local var "unprotected2"
  declared at tc21_pthonce.c:51, in frame #0 of thread 2

ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
